### PR TITLE
Update Connector Quickstart to 7.0.0.SR1

### PR DESCRIPTION
**Pull request by igdianov**

### CODE REVIEW

**Comment by igdianov** [comment]
@salaboy I can revert the commit if you strongly disagree, but in my experience, if you throw exception to `nack` the message right now, it will be retried indefinitely whether you want it or not. In this case, there is no way to propagate the error into Rb, so the connector consumer will be stuck forever retrying failed message. The only way to propagate the error is using variables, like so:

image

There is no alternative right now to enable propagating connector errors without variables using native Spring Cloud Stream messaging.

In theory, it is possible to configure RabbitMQ specific consumer binding to move failing message to DLQ after # of retries limit is reached to break the loop, but in this case the response will not be generated and the process in Rb will be stuck forever. Theoretically, Rb can consume dead messages from the same DLQ. But then, what is the behavior is going to be? How do you specify what should happen in BPMN model if there is an exception in the Connector task? What if someone cancels the process, while connector is stuck in the loop? 

image

**Comment by salaboy** [comment]
@igdianov yes, I feel strongly, and as you mention we don't have the mechanism to deal correctly with the problem, that means that we can prioritise the creation of that mechanism. 
I would like to use https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit#spring-cloud-stream-overview-error-handling and make sure that error handling is uniformly.

The flow in my head should work like this:
**If something fails in the connector logic with an Exception **
1) it will be retried X amount of times based on configurations
2) If the error persist it should go to a DLQ
3) We should have DLQ consumers to report business exceptions to business processes

Let's create an issue to track down this important feature, instead of promoting fixes with variables in the example layer

**Comment by salaboy** [comment]
Done: https://github.com/Activiti/Activiti/issues/2712

**Comment by igdianov** [comment]
@salaboy I have reverted the connector test example commit: https://github.com/Activiti/activiti-cloud-connector-quickstart/pull/8/commits/7531860145bd50267f1690ea240ceadd7c9b51f8

**Pull request merged**
